# encoding: UTF-8
---

resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/riddopic/flight-school
    branch: master

jobs:
- name: test-app
  plan:
  - get: flight-school
  - task: tests
    file: flight-school/build.yml
